// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/assemble" | "/bench" | "/builder" | "/check" | "/coach" | "/inventory" | "/timeline"
type AppRouteHandlerRoutes = "/api/assess" | "/api/bench" | "/api/bench/test" | "/api/coach" | "/api/codegen" | "/api/commits" | "/api/commits/[id]" | "/api/commits/fork" | "/api/commits/rollback-plan" | "/api/flash" | "/api/identify" | "/api/images/[...path]" | "/api/journal" | "/api/live-captures" | "/api/perceive" | "/api/photos" | "/api/photos/[id]" | "/api/photos/[id]/file" | "/api/plan" | "/api/wireplan"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/assess": {}
  "/api/bench": {}
  "/api/bench/test": {}
  "/api/coach": {}
  "/api/codegen": {}
  "/api/commits": {}
  "/api/commits/[id]": { "id": string; }
  "/api/commits/fork": {}
  "/api/commits/rollback-plan": {}
  "/api/flash": {}
  "/api/identify": {}
  "/api/images/[...path]": { "path": string[]; }
  "/api/journal": {}
  "/api/live-captures": {}
  "/api/perceive": {}
  "/api/photos": {}
  "/api/photos/[id]": { "id": string; }
  "/api/photos/[id]/file": { "id": string; }
  "/api/plan": {}
  "/api/wireplan": {}
  "/assemble": {}
  "/bench": {}
  "/builder": {}
  "/check": {}
  "/coach": {}
  "/inventory": {}
  "/timeline": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
