// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/assemble/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assemble">> = Specific
  const handler = {} as typeof import("../../app/assemble/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bench/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bench">> = Specific
  const handler = {} as typeof import("../../app/bench/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/builder">> = Specific
  const handler = {} as typeof import("../../app/builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/check">> = Specific
  const handler = {} as typeof import("../../app/check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/coach/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/coach">> = Specific
  const handler = {} as typeof import("../../app/coach/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../app/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/timeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/timeline">> = Specific
  const handler = {} as typeof import("../../app/timeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/assess/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assess">> = Specific
  const handler = {} as typeof import("../../app/api/assess/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bench/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bench">> = Specific
  const handler = {} as typeof import("../../app/api/bench/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bench/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bench/test">> = Specific
  const handler = {} as typeof import("../../app/api/bench/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/coach/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/coach">> = Specific
  const handler = {} as typeof import("../../app/api/coach/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/codegen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/codegen">> = Specific
  const handler = {} as typeof import("../../app/api/codegen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/commits/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commits/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/commits/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/commits/fork/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commits/fork">> = Specific
  const handler = {} as typeof import("../../app/api/commits/fork/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/commits/rollback-plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commits/rollback-plan">> = Specific
  const handler = {} as typeof import("../../app/api/commits/rollback-plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/commits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/commits">> = Specific
  const handler = {} as typeof import("../../app/api/commits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/flash/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flash">> = Specific
  const handler = {} as typeof import("../../app/api/flash/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/identify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/identify">> = Specific
  const handler = {} as typeof import("../../app/api/identify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/images/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/images/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/images/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/journal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/journal">> = Specific
  const handler = {} as typeof import("../../app/api/journal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/live-captures/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/live-captures">> = Specific
  const handler = {} as typeof import("../../app/api/live-captures/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/perceive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/perceive">> = Specific
  const handler = {} as typeof import("../../app/api/perceive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/photos/[id]/file/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/photos/[id]/file">> = Specific
  const handler = {} as typeof import("../../app/api/photos/[id]/file/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/photos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/photos/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/photos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/photos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/photos">> = Specific
  const handler = {} as typeof import("../../app/api/photos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plan">> = Specific
  const handler = {} as typeof import("../../app/api/plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wireplan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wireplan">> = Specific
  const handler = {} as typeof import("../../app/api/wireplan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
